- hosts: all
  become: true
  tasks:
    - name: Unconditionally reboot the machine with all defaults
      reboot:

    - name: Reboot a slow machine that might have lots of updates to apply
      reboot:
        reboot_timeout: 3600
